#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-xpp3_min
Version  : 1.1.4c
Release  : 3
URL      : https://repo1.maven.org/maven2/xpp3/xpp3_min/1.1.4c/xpp3_min-1.1.4c.jar
Source0  : https://repo1.maven.org/maven2/xpp3/xpp3_min/1.1.4c/xpp3_min-1.1.4c.jar
Source1  : https://repo1.maven.org/maven2/xpp3/xpp3_min/1.1.4c/xpp3_min-1.1.4c.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Public-Domain
Requires: mvn-xpp3_min-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-xpp3_min package.
Group: Data

%description data
data components for the mvn-xpp3_min package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/xpp3/xpp3_min/1.1.4c
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/xpp3/xpp3_min/1.1.4c/xpp3_min-1.1.4c.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/xpp3/xpp3_min/1.1.4c
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/xpp3/xpp3_min/1.1.4c/xpp3_min-1.1.4c.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/xpp3/xpp3_min/1.1.4c/xpp3_min-1.1.4c.jar
/usr/share/java/.m2/repository/xpp3/xpp3_min/1.1.4c/xpp3_min-1.1.4c.pom
